   name: build & deploy spring app

   on:
     push:
       branches:
         - main


   jobs:
     build-deploy:
       name: build and deploy spring boot project
       runs-on: ubuntu-latest
       services:
         postgres:
           image: postgres:latest
           env:
             POSTGRES_DB: sopra-helper
             POSTGRES_USER: postgres
             POSTGRES_PASSWORD: admin
           ports:
             - 5432:5432
           options: >-
             --health-cmd pg_isready
             --health-interval 10s
             --health-timeout 5s
             --health-retries
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup JDK 17
           uses: actions/setup-java@v3
           with:
             distribution: 'corretto'
             java-version: 17

         - name: Unit Tests
           run: mvn -B test --file pom.xml

         - name: Build the application
           run: |
             mvn clean
             mvn -B package --file pom.xml
           
          
          
           
         
        
           
